In [ ]:
import numpy as np
x = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]])
y = np.array([[1,0],   
              [0,1],
              [0,1],
              [1,0]])
np.random.seed(1)
w1 = np.random.randn(2,8)
b1 = np.zeros((1,8))
w2 = np.random.randn(8,6)
b2 = np.zeros((1,6))
w3 = np.random.randn(6,4)
b3 = np.zeros((1,4))
w4 = np.random.randn(4,2)
b4 = np.zeros((1,2))
lr = 0.66
epochs = 500
def sigmoid(z): return 1/(1+np.exp(-z))
def dsigmoid(a): return a*(1-a)
def tanh(z): return np.tanh(z)
def dtanh(a): return 1-a**2
def relu(z): return np.maximum(0,z)
def drelu(z): return (z>0).astype(float)
def softmax(z):
    exp_z = np.exp(z - np.max(z,axis=1,keepdims=True))
    return exp_z / np.sum(exp_z,axis=1,keepdims=True)
def swish(z): return z*sigmoid(z)
def dswish(z): return swish(z) + sigmoid(z)*(1-swish(z))
def train(activation_hidden, activation_output, dactivation_hidden):
    global w1,w2,w3,w4,b1,b2,b3,b4
    w1 = np.random.randn(2,8); b1 = np.zeros((1,8))
    w2 = np.random.randn(8,6); b2 = np.zeros((1,6))
    w3 = np.random.randn(6,4); b3 = np.zeros((1,4))
    w4 = np.random.randn(4,2); b4 = np.zeros((1,2))
    for epoch in range(epochs):
        z1 = x@w1 + b1; a1 = activation_hidden(z1)
        z2 = a1@w2 + b2; a2 = activation_hidden(z2)
        z3 = a2@w3 + b3; a3 = activation_hidden(z3)
        z4 = a3@w4 + b4; output = activation_output(z4)
        loss = np.mean((output-y)**2)
        d_output = (output-y)
        dw4 = a3.T @ d_output
        db4 = np.sum(d_output,axis=0,keepdims=True)
        da3 = d_output @ w4.T
        dz3 = da3 * dactivation_hidden(a3)
        dw3 = a2.T @ dz3
        db3 = np.sum(dz3,axis=0,keepdims=True)
        da2 = dz3 @ w3.T
        dz2 = da2 * dactivation_hidden(a2)
        dw2 = a1.T @ dz2
        db2 = np.sum(dz2,axis=0,keepdims=True)
        da1 = dz2 @ w2.T
        dz1 = da1 * dactivation_hidden(a1)
        dw1 = x.T @ dz1
        db1 = np.sum(dz1,axis=0,keepdims=True)
        w4 -= lr*dw4; b4 -= lr*db4
        w3 -= lr*dw3; b3 -= lr*db3
        w2 -= lr*dw2; b2 -= lr*db2
        w1 -= lr*dw1; b1 -= lr*db1
        if epoch % 100 == 0:
            print(f"Epoch {epoch}, Loss: {loss:.4f}")
            print("Predictions:\n", output)
print("Using Sigmoid")
train(sigmoid, sigmoid, dsigmoid)

print("Using Tanh")
train(tanh, sigmoid, dtanh)

print("Using ReLU")
train(relu, sigmoid, drelu)

print("Using Swish")
train(swish, sigmoid, dswish)

print("Using Softmax")
train(relu, softmax, drelu)


Using Sigmoid
Epoch 0, Loss: 0.2827
Predictions:
 [[0.74566418 0.43268725]
 [0.74907052 0.42675755]
 [0.74525238 0.43515679]
 [0.74737091 0.4263631 ]]
Epoch 100, Loss: 0.2221
Predictions:
 [[0.5306223  0.45524023]
 [0.57070019 0.4127098 ]
 [0.39277722 0.65942844]
 [0.54029393 0.4440183 ]]
Epoch 200, Loss: 0.1695
Predictions:
 [[0.65379872 0.34493685]
 [0.02836625 0.9770025 ]
 [0.66181585 0.33527627]
 [0.65569805 0.34261538]]
Epoch 300, Loss: 0.1675
Predictions:
 [[0.66355028 0.336318  ]
 [0.0069109  0.99384324]
 [0.6658489  0.33365706]
 [0.6637775  0.33604139]]
Epoch 400, Loss: 0.1671
Predictions:
 [[0.66497591 0.33497744]
 [0.00378384 0.99653464]
 [0.66625996 0.33351187]
 [0.66503037 0.3349067 ]]
Using Tanh
Epoch 0, Loss: 0.2990
Predictions:
 [[0.5        0.5       ]
 [0.59571601 0.75558832]
 [0.45549522 0.22403669]
 [0.68625218 0.75437464]]
Epoch 100, Loss: 0.4442
Predictions:
 [[0.94018172 0.05907147]
 [0.94047393 0.05872115]
 [0.94017002 0.0590855 ]
 [0.94015398 0.05910474]]
Epoch 

C:\Users\23adsb66\AppData\Local\Temp\ipykernel_19072\4147863452.py:32: RuntimeWarning: overflow encountered in exp
  def sigmoid(z): return 1/(1+np.exp(-z))
